# Generated by Django 2.2.3 on 2019-07-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decText', models.TextField(blank=True, null=True)),
                ('encText', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
