# Generated by Django 2.2.3 on 2019-07-01 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='AllData',
        ),
    ]
