# Generated by Django 2.2.3 on 2019-07-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alldata_finder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldata',
            name='finder',
            field=models.CharField(max_length=50),
        ),
    ]
