# Generated by Django 2.2.3 on 2019-07-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190702_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldata',
            name='finder',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
