# Generated by Django 2.2.2 on 2019-07-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alldata_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldata',
            name='finder',
            field=models.CharField(max_length=50),
        ),
    ]
