# Generated by Django 2.2.2 on 2019-07-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190702_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alldata',
            name='decText',
        ),
    ]
